@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE5ODkzOTB9.ID5-Z3siD7_7tzv9TTT9ePpuqT0YUmwAuP6dytmcaSE

### Wines Index
GET http://localhost:3000/wines.json

### Wines Create
POST http://localhost:3000/wines.json
Content-Type: application/json

{
  "name": "Test name 2",
  "producer": "Test Producer",
  "vintage": 2022,
  "blend": "Test blend",
  "price": 5.99
}

### Wines Show
GET http://localhost:3000/wines/1.json

### Wines Update
PATCH http://localhost:3000/wines/7.json
Content-Type: application/json

{
  "name": "Test name",
  "producer": "Test Producer",
  "vintage": 2021,
  "blend": "Test blend",
  "price": 4.99
}

### Wines Destroy
DELETE http://localhost:3000/wines/10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### User Wine Index
GET http://localhost:3000/user_wines.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Show
GET http://localhost:3000/user_wines/1.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Create
POST http://localhost:3000/user_wines.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "wine_id": 4
  
}
