@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI0MDU1MDJ9.cOn9ZflB8inRN2Qa_UfUTOgsHWKMzk2qKmnoKXXPu4s
Rosé

### Wines Index
GET http://localhost:3000/wines.json

### Category Wine Create
POST http://localhost:3000/category_wines.json
Content-Type: application/json

{
  "category_id": "8",
  "wine_id": "34"
}

### Wines Create
POST http://localhost:3000/wines.json
Content-Type: application/json

{
  "name": "Charles de Marques Champagne",
  "blend": "Pinot Noir, Pinot Meunier",
  "origin_id": 1,
  "price": 19.99,
  "style": "Fresh, round, and balanced",
  "description": "Toasty brioche, with red apple, citrus, and a hint of rosemary."
}

### Wines Show
GET http://localhost:3000/wines/12.json

### Wines Update
PATCH http://localhost:3000/wines/33.json
Content-Type: application/json

{
  "name": "Finca Flichman Gestos Malbec"
}

### Wines Destroy
DELETE http://localhost:3000/wines/10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "michael@test.com",
  "password": "password"
}

### User Wine Index
GET http://localhost:3000/user_wines.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Show
GET http://localhost:3000/user_wines/1.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Create
POST http://localhost:3000/user_wines.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "wine_id": 9,
  
}

### User Show
GET http://localhost:3000/users/1.json
Content-Type: application/json
