@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE5MDY1NjR9.uCdKGB4L2lgSnMg2_xZs3skFCk-kEePPFChg7u68RH8

### Wines Index
GET http://localhost:3000/wines.json

### Wines Create
POST http://localhost:3000/wines.json
Content-Type: application/json

{
  "name": "Test name 2",
  "producer": "Test Producer",
  "vintage": 2022,
  "blend": "Test blend",
  "price": 5.99
}

### Wines Show
GET http://localhost:3000/wines/1.json

### Wines Update
PATCH http://localhost:3000/wines/7.json
Content-Type: application/json

{
  "name": "Test name",
  "producer": "Test Producer",
  "vintage": 2021,
  "blend": "Test blend",
  "price": 4.99
}

### Wines Destroy
DELETE http://localhost:3000/wines/10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Michael",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "michael@test.com",
  "password": "password"
}

### User Wine Index
GET http://localhost:3000/user_wines.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Show
GET http://localhost:3000/user_wines/1.json
Content-Type: application/json  
Authorization: Bearer {{jwt}}

### User Wine Create
POST http://localhost:3000/user_wines.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "wine_id": 2
}
