User.create!([
  {name: "Michael", email: "michael@test.com", password_digest: "$2a$12$gCG9HzT9DJ67GGbXmGs00O5oghLgTWQp.Cl.0BGGPokq7/3yrOx6i"},
  {name: "Caryn", email: "caryn@test.com", password_digest: "$2a$12$.2drYPp4Rrh7tW0uy.qgkuEhDgdtLnnEvThE2YnaXAfLBU/u3Do8."}
])
Category.create!([
  {name: "Red"},
  {name: "White"},
  {name: "Rosé"},
  {name: "Orange"},
  {name: "Sparkling"},
  {name: "Vegan"},
  {name: "Oaked"},
  {name: "Dry"},
  {name: "Sweet"},
  {name: "Full-Bodied"},
  {name: "Fruity"},
  {name: "Box"},
  {name: "Buttery"}
])
Origin.create!([
  {country: "France"},
  {country: "Portugal"},
  {country: "United States"},
  {country: "Italy"},
  {country: "New Zealand"},
  {country: "Hungary"},
  {country: "Germany"},
  {country: "Australia"},
  {country: "South Africa"},
  {country: "Argentina"}
])
Wine.create!([
  {name: "Casone Toscana IGT", blend: "Sangiovese, Syrah ", price: "10.99", origin_id: 4, style: "Big, bold, and  complex", description: "Expansive and refined flavors accentuate a large tannic  structure with hints of wood and leather."},
  {name: "Cecilia Beretta Prosecco Rosé", blend: "Glera, Pinot Nero ", price: "10.99", origin_id: 4, style: "Vibrant, floral and fruity, crisp and refreshing", description: "Notes of raspberries, fruity but, with good body, bubbly with a clean, crisp finish."},
  {name: "Cecilia Beretta Conegliano Valdobbiadene Prosecco Superiore ", blend: "Glera", price: "10.99", origin_id: 4, style: "Dry, citrusy, and lively", description: "Intense and fruity with tropical fruits, acacia, and notes of  white flowers leading to crisp  acidity with citrus hints."},
  {name: "Cecilia B. Vino Spumante Rosé", blend: "Glera, Raboso", price: "7.99", origin_id: 4, style: "Crisp and refreshing", description: "Fresh on the nose with notes of pear and red fruit, leading to a dry palate with notes of red fruit  and acidity."},
  {name: "Cecilia Beretta Valpolicella Ripasso", blend: "Corvina, Rondinella,  Corvinone, Negrara", price: "9.99", origin_id: 4, style: "Rich & sweet", description: "Intense aromas of wild cherries, red currant and hints of toasting. A rich, full-bodied wine, with sweet and round tannins."},
  {name: "Château de Seguin Bordeaux Supérieur", blend: "Merlot, Cabernet Sauvignon, Cabernet Franc, Malbec", price: "11.99", origin_id: 1, style: "Bold and full-bodied", description: "Blackcurrants and cherry with hints of coffee, vanilla and oak with well-balanced tannins"},
  {name: "The Delicious Monster", blend: "Chenin Blanc, Chardonnay, Hanepoot, Columbar", price: "5.99", origin_id: 9, style: "Balanced and crisp", description: "The balance of fruit, acid, and sweetness brings out the  flavors in harmony to create a  refreshing, easy-drinking wine."},
  {name: "Dr. Beckermann Rheinhessen Auslese", blend: "Riesling, Muller Thurgau, Silvaner, Kerner", price: "6.99", origin_id: 7, style: "Fruity and sweet", description: "Notes of nectarine and pink grapefruit with a sweet honey  finish."},
  {name: "Espiral Vinho Verde", blend: "Loureiro, Pederna, Trajadura, Azal", price: "4.49", origin_id: 2, style: "Dry and aromatic", description: "Green apple, melon, and slight bubbles."},
  {name: "Block White Wine Pinot Grigio", blend: "Pinot Grigio", price: "12.99", origin_id: 4, style: "Clean and crisp", description: "Crisp, fresh, fruity aromas with notes of citrus and pear, and a nice, clean finish."},
  {name: "Almond Creek Sparkling Wine", blend: "Chardonnay", price: "6.99", origin_id: 3, style: "Sweet, bubbly, and amandine", description: "Crisp and bubbly with marzipan and other nutty flavors and  subtly sweet aftertaste."},
  {name: "Emma Reichart Dry Riesling", blend: "Riesling", price: "4.99", origin_id: 7, style: "Bright and citrusy", description: "Aromatics of fragrant citrus blossom with a profile of apricot, meyer lemon, and honeycomb."},
  {name: "Baron de Taste Reserve Margaux", blend: "Merlot, Cabernet Sauvignon", price: "14.99", origin_id: 1, style: "Savory and classic", description: "Aromatic with black fruits and baking spices. Smooth tannins with toasted oak and a long, intense finish."},
  {name: "Emma Reichart Pinot Noir Rosé", blend: "Pinot Noir", price: "4.99", origin_id: 7, style: "Crisp and dry", description: "Refreshing notes of tart cherry, red currant, and a touch of watermelon."},
  {name: "Barrel Heist Bourbon Barrel Aged Cabernet Sauvignon", blend: "Cabernet Sauvignon", price: "7.99", origin_id: 3, style: "Robust and fruit-forward", description: "Notes of vanilla, caramel, and dark spices."},
  {name: "Bay Moon Sauvignon Blanc", blend: "Sauvignon Blanc", price: "5.99", origin_id: 3, style: "Crisp, citrusy, and unoaked", description: "Grapefruit, lime blossom, and lemon grass with lively acidity"},
  {name: "Belles Vignes Sauvignon Blanc", blend: "Sauvignon Blanc", price: "6.99", origin_id: 1, style: "Expressive and fresh", description: "Floral and light vegetal notes on the nose, with a lively, floral, and refreshing palate."},
  {name: "Big Churn Chardonnay", blend: "Chardonnay", price: "6.99", origin_id: 3, style: "Very oaky and buttery", description: "Toasty vanilla, ripe baked apple, pear, and tropical fruit -  and, of course, butter."},
  {name: "Block Red Wine Shiraz", blend: "Shiraz", price: "12.99", origin_id: 8, style: "Smooth and dry, but fruit  forward", description: "Blackberry, currant, and hints of fig with a smooth finish."},
  {name: "Fior di Vino Chianti Classico Riserva", blend: "Sangiovese, Cabernet Sauvignon", price: "6.99", origin_id: 4, style: "Bold and Balanced", description: "Intense, dark ruby color with notes of plums, blackberry, and raspberry fruit."},
  {name: "Butler Pond Pinot Noir", blend: "Pinot Noir, Barbera, Gamay", price: "6.99", origin_id: 3, style: "Bright & complex", description: "Bright structure with notes of cherry cream soda, toasted  brioche, and cranberry."},
  {name: "Ca'Storica Amarone della Valpolicella", blend: "Corvina, Rondinealla, Molinara", price: "15.99", origin_id: 4, style: "Bold with a long and silky finish", description: "Notes of ripe cherry, raspberry, cocoa and dried fruit."},
  {name: "Ca'Belli Prosecco Extra Dry", blend: "Glera", price: "7.99", origin_id: 4, style: "Fruit forward and fresh", description: "Notes of citrus fruit, lemon skin, ripe peach, and a hint of honey."},
  {name: "Ca'Belli Prosecco Rosé", blend: "Glera, Pinot Noir", price: "8.99", origin_id: 4, style: "Crisp and refreshing", description: "Fruity aromas of cherry and berry on the nose with delicate floral notes."},
  {name: "Carayon La Rose Rosé", blend: "Grenache, Syrah", price: "6.99", origin_id: 1, style: "Dry, crisp, and refreshing", description: "Strawberry and subtle melon notes with a dry, refreshing  mouth feel."},
  {name: "Caretaker Cabernet Sauvignon", blend: "Cabernet Sauvignon, Petite Sirah, Merlot", price: "9.99", origin_id: 3, style: "Bold and full-bodied", description: "Big flavors of plum and cherry with spicy cassis aromas."},
  {name: "Caretaker Pinot Noir", blend: "Pinot Noir", price: "9.99", origin_id: 3, style: "Medium-bodied and smooth", description: "Black cherry and candied ginger with dark cocoa, raspberries, and plush tannins."},
  {name: "Floriana Grüner Veltliner", blend: "Grüner Veltliner, Chardonnay", price: "5.99", origin_id: 6, style: "Dry and aromatic", description: "Bone dry and fruity with aromas of green apple and kiwi with crisp and refreshing acidity."},
  {name: "Ruggero di Bardo Susumaniello", blend: "Susumaniello", price: "10.99", origin_id: 4, style: "Fresh and fruity", description: "On the nose, blueberries and ripe red fruits, underbrush and red flower, then tobacco, aromatic herbs and a light zesty sensation."},
  {name: "Domaine de la Vauvise Sancerre", blend: "Sauvignon Blanc", price: "18.99", origin_id: 1, style: "Vivacious and fruity", description: "Full floral aromatics, with flavors of juicy citrus and flinty minerals."},
  {name: "Grifone 1967 Toscana Rosso IGT", blend: "Sangiovese, Cabernet Sauvignon, Syrah", price: "6.99", origin_id: 4, style: "Smooth and dry, but fruit-forward", description: "Cherry, plum, and blackberry with gentle vanilla and oak  notes."},
  {name: "Kono Sauvignon Blanc", blend: "Sauvignon Blanc", price: "8.99", origin_id: 5, style: "Crisp and floral, with grassy notes", description: "Generous, juicy flavors of melon, grapefuit and kiwi with tempering acidity and fine mineral notes."},
  {name: "Finca Flichman Gestos Malbec", blend: "Malbec", price: "8.99", origin_id: 10, style: "Bold and full bodied", description: "Plums and oak on the nose with a concentrated profile of dark fruit and chocolate."},
  {name: "Charles de Marques Champagne", blend: "Pinot Noir, Pinot Meunier", price: "19.99", origin_id: 1, style: "Fresh, round, and balanced", description: "Toasty brioche, with red apple, citrus, and a hint of rosemary."}
])
CategoryWine.create!([
  {wine_id: 1, category_id: 2},
  {wine_id: 1, category_id: 5},
  {wine_id: 1, category_id: 8},
  {wine_id: 2, category_id: 2},
  {wine_id: 2, category_id: 5},
  {wine_id: 2, category_id: 9},
  {wine_id: 3, category_id: 1},
  {wine_id: 3, category_id: 10},
  {wine_id: 3, category_id: 7},
  {wine_id: 3, category_id: 8},
  {wine_id: 4, category_id: 1},
  {wine_id: 4, category_id: 6},
  {wine_id: 4, category_id: 7},
  {wine_id: 4, category_id: 10},
  {wine_id: 4, category_id: 11},
  {wine_id: 5, category_id: 2},
  {wine_id: 5, category_id: 8},
  {wine_id: 6, category_id: 2},
  {wine_id: 6, category_id: 6},
  {wine_id: 6, category_id: 8},
  {wine_id: 7, category_id: 2},
  {wine_id: 7, category_id: 7},
  {wine_id: 7, category_id: 13},
  {wine_id: 8, category_id: 2},
  {wine_id: 8, category_id: 6},
  {wine_id: 8, category_id: 8},
  {wine_id: 8, category_id: 12},
  {wine_id: 9, category_id: 12},
  {wine_id: 9, category_id: 1},
  {wine_id: 9, category_id: 6},
  {wine_id: 9, category_id: 7},
  {wine_id: 9, category_id: 8},
  {wine_id: 9, category_id: 11},
  {wine_id: 10, category_id: 1},
  {wine_id: 10, category_id: 11},
  {wine_id: 11, category_id: 1},
  {wine_id: 11, category_id: 6},
  {wine_id: 11, category_id: 7},
  {wine_id: 11, category_id: 10},
  {wine_id: 12, category_id: 2},
  {wine_id: 12, category_id: 5},
  {wine_id: 12, category_id: 6},
  {wine_id: 12, category_id: 8},
  {wine_id: 13, category_id: 3},
  {wine_id: 13, category_id: 5},
  {wine_id: 13, category_id: 6},
  {wine_id: 13, category_id: 11},
  {wine_id: 14, category_id: 3},
  {wine_id: 14, category_id: 6},
  {wine_id: 14, category_id: 8},
  {wine_id: 15, category_id: 1},
  {wine_id: 15, category_id: 6},
  {wine_id: 15, category_id: 7},
  {wine_id: 15, category_id: 8},
  {wine_id: 15, category_id: 10},
  {wine_id: 16, category_id: 1},
  {wine_id: 16, category_id: 6},
  {wine_id: 16, category_id: 8},
  {wine_id: 16, category_id: 11},
  {wine_id: 17, category_id: 1},
  {wine_id: 17, category_id: 7},
  {wine_id: 17, category_id: 8},
  {wine_id: 17, category_id: 10},
  {wine_id: 18, category_id: 3},
  {wine_id: 18, category_id: 5},
  {wine_id: 18, category_id: 11},
  {wine_id: 19, category_id: 2},
  {wine_id: 19, category_id: 5},
  {wine_id: 19, category_id: 6},
  {wine_id: 19, category_id: 8},
  {wine_id: 20, category_id: 3},
  {wine_id: 20, category_id: 5},
  {wine_id: 20, category_id: 8},
  {wine_id: 20, category_id: 11},
  {wine_id: 21, category_id: 1},
  {wine_id: 21, category_id: 6},
  {wine_id: 21, category_id: 7},
  {wine_id: 21, category_id: 9},
  {wine_id: 21, category_id: 10},
  {wine_id: 22, category_id: 1},
  {wine_id: 22, category_id: 6},
  {wine_id: 22, category_id: 7},
  {wine_id: 22, category_id: 8},
  {wine_id: 22, category_id: 10},
  {wine_id: 23, category_id: 2},
  {wine_id: 23, category_id: 6},
  {wine_id: 23, category_id: 8},
  {wine_id: 23, category_id: 11},
  {wine_id: 24, category_id: 2},
  {wine_id: 24, category_id: 9},
  {wine_id: 24, category_id: 11},
  {wine_id: 25, category_id: 2},
  {wine_id: 25, category_id: 6},
  {wine_id: 25, category_id: 8},
  {wine_id: 26, category_id: 3},
  {wine_id: 26, category_id: 8},
  {wine_id: 26, category_id: 11},
  {wine_id: 27, category_id: 1},
  {wine_id: 27, category_id: 7},
  {wine_id: 27, category_id: 8},
  {wine_id: 28, category_id: 2},
  {wine_id: 28, category_id: 8},
  {wine_id: 28, category_id: 6},
  {wine_id: 28, category_id: 11},
  {wine_id: 29, category_id: 1},
  {wine_id: 29, category_id: 6},
  {wine_id: 29, category_id: 7},
  {wine_id: 29, category_id: 11},
  {wine_id: 30, category_id: 2},
  {wine_id: 30, category_id: 6},
  {wine_id: 30, category_id: 8},
  {wine_id: 31, category_id: 1},
  {wine_id: 31, category_id: 6},
  {wine_id: 31, category_id: 7},
  {wine_id: 31, category_id: 8},
  {wine_id: 31, category_id: 11},
  {wine_id: 32, category_id: 2},
  {wine_id: 32, category_id: 6},
  {wine_id: 32, category_id: 8},
  {wine_id: 33, category_id: 1},
  {wine_id: 33, category_id: 6},
  {wine_id: 33, category_id: 7},
  {wine_id: 33, category_id: 8},
  {wine_id: 33, category_id: 10},
  {wine_id: 34, category_id: 2},
  {wine_id: 34, category_id: 5},
  {wine_id: 34, category_id: 6},
  {wine_id: 34, category_id: 7},
  {wine_id: 34, category_id: 8}
])
